# Generated by Django 4.2.25 on 2025-10-05 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_representante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Representante',
                'verbose_name_plural': 'Perfiles de Representante',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_por_bloque', models.PositiveIntegerField(default=20)),
                ('maximo_citas_diarias', models.PositiveIntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfiles de Docente',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_estudiante', models.CharField(max_length=100)),
                ('nombre_estudiante', models.CharField(max_length=120)),
                ('motivo', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='turnos.perfildocente')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ('docente', 'inicio'),
                'indexes': [models.Index(fields=['docente', 'inicio'], name='turnos_cita_docente_32aad5_idx'), models.Index(fields=['estado'], name='turnos_cita_estado_adc544_idx'), models.Index(fields=['inicio'], name='turnos_cita_inicio_d18263_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('docente', 'inicio', 'fin'), name='unica_cita_docente_rango'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(check=models.Q(('fin__gt', models.F('inicio'))), name='cita_fin_gt_inicio'),
        ),
    ]
