# Generated by Django 4.2.25 on 2025-10-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('BLOQUEO', 'Bloqueo'), ('EXTRA', 'Extra')], default='BLOQUEO', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='turnos.perfildocente')),
            ],
            options={
                'verbose_name': 'Excepción de disponibilidad',
                'verbose_name_plural': 'Excepciones de disponibilidad',
                'indexes': [models.Index(fields=['docente', 'fecha'], name='turnos_exce_docente_88a205_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='turnos.perfildocente')),
            ],
            options={
                'verbose_name': 'Disponibilidad semanal',
                'verbose_name_plural': 'Disponibilidades semanales',
                'indexes': [models.Index(fields=['docente', 'dia_semana'], name='turnos_disp_docente_85d2d1_idx')],
                'unique_together': {('docente', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
