# Generated by Django 4.2.25 on 2025-10-16 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0002_excepciondisponibilidad_disponibilidadsemanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,20}$', 'Cédula inválida (solo dígitos, 8-20).')])),
                ('curso', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['curso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionRepresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=40)),
                ('verificado', models.BooleanField(default=False)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Importación')], default='MANUAL', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='turnos.estudiante')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_representacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Representación',
                'verbose_name_plural': 'Relaciones de Representación',
            },
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['curso'], name='turnos_estu_curso_851fce_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['activo'], name='turnos_estu_activo_bcde1a_idx'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='turnos.estudiante'),
        ),
        migrations.AddIndex(
            model_name='relacionrepresentacion',
            index=models.Index(fields=['representante'], name='turnos_rela_represe_d0f997_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionrepresentacion',
            index=models.Index(fields=['estudiante'], name='turnos_rela_estudia_06925e_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionrepresentacion',
            index=models.Index(fields=['activo'], name='turnos_rela_activo_780ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionrepresentacion',
            index=models.Index(fields=['verificado'], name='turnos_rela_verific_67c750_idx'),
        ),
        migrations.AddConstraint(
            model_name='relacionrepresentacion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'representante'), name='unica_relacion_estudiante_representante'),
        ),
    ]
