# Generated by Django 4.2.25 on 2025-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_estudiante_relacionrepresentacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feriado/Evento institucional',
                'verbose_name_plural': 'Feriados/Eventos institucionales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
